### ISSUE TITLE
Why is the directory structure Sources/<TARGET>?

### ISSUE THREAD

**Issue by AndrewSB** [DeskConnect/WFOAuth2#1]
Is that an alternative to a single Source directory for the Swift Package Manager? So you could potentially have multiple targets in the same xcodeproj?

I haven't seen it done that way before

**Comment by conradev** [comment]
Yes, it's so that I can add additional targets in the future if I want to. Namely, a Swift wrapper.

**Comment by AndrewSB** [comment]
💯

extensible
